namespace SDE
{
    public static class SdeStrings
    {
        #region Shortcut commands

        public const string AutoGenerated = "#auto_generated";
        public const string LineFeed = "\r\n";

        #endregion Shortcut commands
    }
}