using System.Linq;

namespace SDE.Tools.DatabaseEditor.Objects.Items {
	public static class ItemHelper {
		public static string[] Jobs = {
			"--- Specials and generic ---",
			"Novice",
			"Every Job",
			"Every 2nd Job or above",
			"Every 3rd Job",
			"Every Job Except Novice",
			"Every Rebirth Job except High Novice",
			"Every Rebirth Job or above",
			" ",
			"--- 1st Job Class ---",
			"Acolyte Class",
			"Archer Class",
			"Mage Class",
			"Merchant Class",
			"Swordman Class",
			"Thief Class",
			"  ",
			"--- 2nd Job Class ---",
			"Alchemist",
			"Assassin",
			"Bard",
			"Blacksmith",
			"Crusader",
			"Dancer",
			"Hunter",
			"Knight",
			"Monk",
			"Priest",
			"Rogue",
			"Sage",
			"Wizard",
			"   ",
			"--- Rebirth 2nd Job Class ---",
			"Assassin Cross",
			"Biochemist",
			"Champion",
			"Clown",
			"Gypsy",
			"High Priest",
			"High Wizard",
			"Lord Knight",
			"Paladin",
			"Scholar",
			"Sniper",
			"Stalker",
			"Whitesmith",
			"    ",
			"--- 3rd Job Class ---",
			"Arch Bishop",
			"Geneticist",
			"Guillotine Cross",
			"Maestro",
			"Mechanic",
			"Ranger",
			"Royal Guard",
			"Rune Knight",
			"Shadow Chaser",
			"Sorcerer",
			"Sura",
			"Wanderer",
			"Warlock",
			"     ",
			"--- Extended Class ---",
			"Gunslinger",
			"Ninja",
			"Soul Linker",
			"Super Novice",
			"Taekwon",
			"Taekwon Master",
			"Gangsi",
			"Death Knight",
			"Dark Collector",
			"Kagerou",
			"Oboro",
			"Rebellion"
		};

		public static bool ComparesTo(string itemClass, params string[] values) {
			string itemClassLower = itemClass.ToLower().Trim(' ');
			return values.Any(val => itemClassLower == val.ToLower());
		}
	}
}
